# Generated by Django 4.1.2 on 2022-11-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_tradingcard_wishlist_sold_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingcard',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
