# Generated by Django 4.1.2 on 2022-12-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_tradingcard_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
