# Generated by Django 4.1.2 on 2022-12-13 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0005_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvv', models.TextField(blank=True, max_length=3)),
                ('credit_card', models.TextField(blank=True, max_length=100)),
                ('owner_name', models.CharField(blank=True, max_length=30)),
                ('date', models.CharField(blank=True, max_length=30)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
