# Generated by Django 4.1.2 on 2022-12-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_userpaymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymentmethod',
            name='credit_card',
            field=models.TextField(blank=True, max_length=16),
        ),
    ]
